#[macro_use]
mod macros;
pub(crate) mod admin;
pub(crate) mod after_stream;
pub(crate) mod alias_admin;
pub(crate) mod auth;
pub(crate) mod clip;
pub(crate) mod command_admin;
pub(crate) mod countdown;
pub(crate) mod eight_ball;
pub(crate) mod gtav;
pub(crate) mod help;
pub(crate) mod misc;
pub(crate) mod poll;
pub(crate) mod promotions;
pub(crate) mod song;
pub(crate) mod speedrun;
pub(crate) mod swearjar;
pub(crate) mod theme_admin;
pub(crate) mod time;
pub(crate) mod water;
pub(crate) mod weather;
