[package]
name = "oxidize-messagelog"
edition = "2021"
publish = false

[dependencies]
bus = { workspace = true }
common = { workspace = true }
emotes = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
